"""empty message

Revision ID: 1ceee760a971
Revises: d2acbd26d370
Create Date: 2021-03-22 19:53:55.681792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ceee760a971'
down_revision = 'd2acbd26d370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proyecto_id_profesional_fkey', 'proyecto', type_='foreignkey')
    op.drop_column('proyecto', 'id_profesional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto', sa.Column('id_profesional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('proyecto_id_profesional_fkey', 'proyecto', 'profesional', ['id_profesional'], ['id'])
    # ### end Alembic commands ###
