"""empty message

Revision ID: 3848ec886200
Revises: 5dc6201e7e26
Create Date: 2021-03-22 15:00:57.000262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848ec886200'
down_revision = '5dc6201e7e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesional', sa.Column('nombre_de_usuario', sa.String(length=120), nullable=False))
    op.alter_column('profesional', 'estado_profesional',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('profesional_username_key', 'profesional', type_='unique')
    op.create_unique_constraint(None, 'profesional', ['nombre_de_usuario'])
    op.drop_column('profesional', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesional', sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profesional', type_='unique')
    op.create_unique_constraint('profesional_username_key', 'profesional', ['username'])
    op.alter_column('profesional', 'estado_profesional',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('profesional', 'nombre_de_usuario')
    # ### end Alembic commands ###
