"""empty message

Revision ID: a13b7f4f8b5b
Revises: 5dc6201e7e26
Create Date: 2021-03-22 17:14:38.272841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13b7f4f8b5b'
down_revision = '5dc6201e7e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesional', 'estado_profesional')
    op.drop_column('proyecto', 'estado')
    op.drop_column('tarea', 'estado_tarea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarea', sa.Column('estado_tarea', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('proyecto', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('profesional', sa.Column('estado_profesional', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
