"""empty message

Revision ID: ad36aaacc716
Revises: 
Create Date: 2021-03-25 03:53:41.577351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad36aaacc716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=120), nullable=False),
    sa.Column('correo_cliente', sa.String(length=120), nullable=False),
    sa.Column('telefono_cliente', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_cliente'),
    sa.UniqueConstraint('correo_cliente')
    )
    op.create_table('profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_usuario', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('profesion', sa.String(length=120), nullable=False),
    sa.Column('cedula_profesional', sa.Integer(), nullable=False),
    sa.Column('nombre_profesional', sa.String(length=120), nullable=False),
    sa.Column('correo_profesional', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_profesional'),
    sa.UniqueConstraint('correo_profesional'),
    sa.UniqueConstraint('nombre_de_usuario')
    )
    op.create_table('proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('nombre_proyecto', sa.String(length=120), nullable=False),
    sa.Column('descripcion_proyecto', sa.String(length=120), nullable=False),
    sa.Column('fecha_entrega', sa.String(length=200), nullable=False),
    sa.Column('horas_totales', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('nombre_tarea', sa.String(length=120), nullable=False),
    sa.Column('fecha_entrega', sa.String(length=150), nullable=False),
    sa.Column('horas_totales', sa.String(length=150), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    op.drop_table('proyecto')
    op.drop_table('profesional')
    op.drop_table('cliente')
    # ### end Alembic commands ###
