"""empty message

Revision ID: d2acbd26d370
Revises: a13b7f4f8b5b
Create Date: 2021-03-22 17:16:50.047797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2acbd26d370'
down_revision = 'a13b7f4f8b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto', sa.Column('descripcion_proyecto', sa.String(length=200), nullable=False))
    op.drop_column('proyecto', 'horas_totales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto', sa.Column('horas_totales', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('proyecto', 'descripcion_proyecto')
    # ### end Alembic commands ###
